[buildpack]
name = "Gradle"

  [publish.Ignore]
  files = [
    "etc/",
    "spec/",
    "test/",
    "vendor/",
    "bin/",
    "gradle/",
    "lib/",
    "opt/",
    ".gitignore",
    ".github/",
    ".travis.yml",
    "circle.yml",
    "hatchet.json",
    "Gemfile",
    "Gemfile.lock",
]
